### ISSUE TITLE
Adding glow to this

### ISSUE THREAD

**Issue by xenu1** [nbqofficial/kernel-csgo#1]
I've fixed errors it seems. Unfortunately can't even get the usermode portion to open. I modified the triggerbot code with glow (took example from 3KB glow) ```
for (int i = 1; i < 65; i++)
			{
				ULONG dwCurrentEntity = driver_control::read_memory<ULONG>(process_id, client_base + m_dwEntityList + i * 0x10);

				if (dwCurrentEntity)
				{
					flSensorTime = 86400.f;
					driver_control::write_memory<ULONG>(process_id, client_base, dwCurrentEntity + 0x3978), & flSensorTime, sizeof(flSensorTime); 
```The exe won't even open unfortunately and the driver is successfully loaded.

**Comment by nbqofficial** [comment]
Reading floats should work just fine iirc. Add me on discord for further questions
