### ISSUE TITLE
Got 2 errors

### ISSUE THREAD

**Issue by N3OA** [nbqofficial/kernel-csgo#5]
Cannot specify [ClassInstall32] section for Microsoft-defined class.
Class "Sample" is reserved for use by Microsoft.

How do i fix this?

**Comment by nbqofficial** [comment]
Are you compiling in release x64? Also do you have wdk installed properly? Because the solution should work out of the box without any additional modifications.

**Comment by N3OA** [comment]
Yes did all of it and got the 2 errors unfortunately.

**Comment by N3OA** [comment]
Why you closed the issue? its not solved lol
